name: random_card_new
description: A new Flutter project for PLO Practice.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  url_launcher_windows: ^3.1.4
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true 
  
  assets:
    - assets/kakao_pay.jpg
    - assets/sounds/

  generate: true # 국제화를 위한 코드 생성 활성화
